---
title: "Peer-graded Assignment: Course Project: Shiny Application and Reproducible Pitch"
author: "Greg Ricci"
date: "3/29/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Introduction: 

I am avid sports car enthusiast and my friends often asked me when was a certain car made and what where the other makes and models produced by that manufacturer. 

I created simple shiny App to assist in filtering sports car data by the car manufacturer and presenting as an output as a data table that displays the following aspects for the selected manufacturer: Model and Style types, Base and span of Production years and the Country of Origin.
 
The next few slides will describe how the Shiny App was created.


## Finding the Data Set

This underlying source data was obtained from the World Wide Web at the following Web Site https://en.wikipedia.org/wiki/List_of_sports_cars.   

The web page is static compilation of sports cars, coupés, roadsters, kit cars, supercars, hyper-cars, electric sport cars, racecars, and super SUVs, both discontinued and still in production. 

Note to user of the App - The site notes that different countries/continents may also classify vehicles differently, for example; the Toyota 86 name is known throughout most of the world. However, in Europe, it's sold as the Toyota GT86, and in the United States and Canada it's sold under the Scion marque as the Scion FR-S (at least, until 2016) and the Subaru marque as the Subaru BRZ. 



## Creating the Application

The data was scraped of the web page and imported into a excel spreadsheet. Utilizing the R library(readxl), I used the read_excel code to bring the data into R.

Then created the ui.R file that creates the main and side panels of the Shiny App and then the server.R file which controls the output of Shiny App. 


## Bringing it all together:

Thank you for taking the time to evaluate my product.

Users may find my Shiny App at the following link:

https://gregriccicpa.shinyapps.io/ShinySpotsCars/


The code for the ui.R and server.R files and additional documentation can be found at the following GitHub repository link:
https://github.com/GregRicciCPA/Shiny-Application-and-Reproducible-Pitch/tree/master

